spring:
  application:
    name: "bootful opensearch"
aws:
  os:
    region: region
    endpoint: "endpoint:port"
  iam:
    role: arn

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus