spring:
  application:
    name: "bootful opensearch"
aws:
  os:
    region: "region"
    endpoint: "url:port"
  iam:
    role: "rolearn"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus